id: I006D4C7E
legacy_id: P003240
ocr_import_info:
  bdrc_scan_id: W3CN3029
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T08:16:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:27:02.322229+00:00'
last_modified: 2022-08-27 19:27:24.794537
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3029
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3029
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྡུས་གྲྭའི་རྩ་བ་ཐུན་མོང་བསྡུས་པའི་བསྡོམ་ཚིག་དང་དེའི་འགྲེལ་པ།
  author: དཀའ་ཆེན་བློ་བཟང་བཟོད་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9661421987158648
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I3CN3488:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3488
      total_pages: 382
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3488.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9661421987158648
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
